spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  jackson:
    serialization:
      indent_output: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carwash_db
    username: postgres
    password: pass
jwt:
  secret-key: "secret-key-secret-key-secret-key-secret-key-secret-key"
  bearer: "Bearer "
  session-time:
    access1: 900000
    access: 86400000
    refresh: 86400000
  auth-header: "Authorization"
