version: '3.3'

services:
  postgres:
    container_name: "car-wash"
    image: 'postgres:13'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_DB=carwash_db'